object Versions {
  val catsCore               = "2.12.0"
  val catsEffect             = "3.5.4"
  val circe                  = "0.14.9"
  val ciris                  = "3.6.0"
  val ducktape               = "0.2.5"
  val flyway                 = "10.17.3"
  val fs2                    = "3.11.0"
  val http4s                 = "0.23.27"
  val ip4s                   = "3.5.0"
  val log4cats               = "2.7.0"
  val logback                = "1.4.14"
  val logstashLogbackEncoder = "8.0"
  val slf4j                  = "2.0.16"
  val natchez                = "0.3.5"
  val otel4s                 = "0.8.0"
  val opentelemetry          = "1.42.0"
  val skunk                  = "1.0.0-M7"
  val sourcepos              = "1.1.0"
  val testContainers         = "0.41.4"
  val twiddles               = "0.8.0"
  val munit                  = "1.0.1"
  val munitCatsEffect        = "2.0.0"
  val scalaParserCombinators = "2.4.0"
  val postgres               = "42.7.4"
  val weaver                 = "0.8.3"
}
