services:
  geolocation-postgres:
    image: 'postgis/postgis:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: scala
      POSTGRES_PASSWORD: scala
      POSTGRES_DB: geolocation
    networks:
      - geolocation-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]

  geolocation:
    image: 'geolocation:latest'
    ports:
      - '8080:8080'
    environment:
      DB_HOST: geolocation-postgres
      DB_PORT: 5432
      DB_USERNAME: scala
      DB_PASSWORD: scala
      DB_DATABASE: geolocation
    depends_on:
      geolocation-postgres:
        condition: service_healthy
        restart: true
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    networks:
      - geolocation-network

networks:
  geolocation-network:
    driver: bridge
